-- MySQL Script generated by MySQL Workbench
-- do 20 jul 2017 15:43:17 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema roadquality
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema roadquality
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roadquality` DEFAULT CHARACTER SET utf8 ;
USE `roadquality` ;

-- -----------------------------------------------------
-- Table `roadquality`.`Devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roadquality`.`Devices` ;

CREATE TABLE IF NOT EXISTS `roadquality`.`Devices` (
  `idDevices` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`idDevices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadquality`.`LinearAccelleration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roadquality`.`LinearAccelleration` ;

CREATE TABLE IF NOT EXISTS `roadquality`.`LinearAccelleration` (
  `idLinearAccelleration` INT NOT NULL AUTO_INCREMENT,
  `deviceId` INT NOT NULL,
  `time` BIGINT NULL,
  `accuracy` FLOAT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `z` FLOAT NULL,
  PRIMARY KEY (`idLinearAccelleration`),
  INDEX `fk_LinearAccelleration_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_LinearAccelleration_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `roadquality`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The Linear Accellerometer gives the accelleration of device.';


-- -----------------------------------------------------
-- Table `roadquality`.`Accelerometer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roadquality`.`Accelerometer` ;

CREATE TABLE IF NOT EXISTS `roadquality`.`Accelerometer` (
  `idAccelerometer` INT NOT NULL AUTO_INCREMENT,
  `deviceId` INT NOT NULL,
  `time` BIGINT NULL,
  `accuracy` FLOAT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `z` FLOAT NULL,
  PRIMARY KEY (`idAccelerometer`),
  INDEX `fk_Accelerometer_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_Accelerometer_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `roadquality`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadquality`.`Gyroscope`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roadquality`.`Gyroscope` ;

CREATE TABLE IF NOT EXISTS `roadquality`.`Gyroscope` (
  `idGyroscope` INT NOT NULL AUTO_INCREMENT,
  `deviceId` INT NOT NULL,
  `time` BIGINT NULL,
  `accuracy` FLOAT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `z` FLOAT NULL,
  PRIMARY KEY (`idGyroscope`),
  INDEX `fk_Gyroscope_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_Gyroscope_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `roadquality`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadquality`.`GPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roadquality`.`GPS` ;

CREATE TABLE IF NOT EXISTS `roadquality`.`GPS` (
  `idGPS` INT NOT NULL AUTO_INCREMENT,
  `deviceId` INT NOT NULL,
  `time` BIGINT NULL,
  `accuracy` FLOAT NULL,
  `lattitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `altitude` FLOAT NULL,
  `bearing` FLOAT NULL,
  `speed` FLOAT NULL,
  PRIMARY KEY (`idGPS`),
  INDEX `fk_GPS_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_GPS_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `roadquality`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
