-- MySQL Script generated by MySQL Workbench
-- do 20 jul 2017 13:53:58 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Devices` (
  `idDevices` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`idDevices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LinearAccelleration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LinearAccelleration` (
  `idLinearAccelleration` INT NOT NULL,
  `deviceId` INT NOT NULL,
  `time` INT NULL,
  `accuracy` FLOAT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `z` FLOAT NULL,
  PRIMARY KEY (`idLinearAccelleration`),
  INDEX `fk_LinearAccelleration_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_LinearAccelleration_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `mydb`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The Linear Accellerometer gives the accelleration of device.';


-- -----------------------------------------------------
-- Table `mydb`.`Accelerometer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accelerometer` (
  `idAccelerometer` INT NOT NULL,
  `deviceId` INT NOT NULL,
  `time` INT NULL,
  `accuracy` FLOAT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `z` FLOAT NULL,
  PRIMARY KEY (`idAccelerometer`),
  INDEX `fk_Accelerometer_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_Accelerometer_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `mydb`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gyroscope`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gyroscope` (
  `idGyroscope` INT NOT NULL,
  `deviceId` INT NOT NULL,
  `time` INT NULL,
  `accuracy` FLOAT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `z` FLOAT NULL,
  PRIMARY KEY (`idGyroscope`),
  INDEX `fk_Gyroscope_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_Gyroscope_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `mydb`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GPS` (
  `idGPS` INT NOT NULL,
  `deviceId` INT NOT NULL,
  `time` INT NULL,
  `accuracy` FLOAT NULL,
  `lattitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `altitude` FLOAT NULL,
  `speed` FLOAT NULL,
  PRIMARY KEY (`idGPS`),
  INDEX `fk_GPS_1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_GPS_1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `mydb`.`Devices` (`idDevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
